/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.newrelic.trace.v1.AttributeValue', null, global);
goog.exportSymbol('proto.com.newrelic.trace.v1.RecordStatus', null, global);
goog.exportSymbol('proto.com.newrelic.trace.v1.Span', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.newrelic.trace.v1.Span = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.newrelic.trace.v1.Span, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.newrelic.trace.v1.Span.displayName = 'proto.com.newrelic.trace.v1.Span';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.newrelic.trace.v1.Span.prototype.toObject = function(opt_includeInstance) {
  return proto.com.newrelic.trace.v1.Span.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.newrelic.trace.v1.Span} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.newrelic.trace.v1.Span.toObject = function(includeInstance, msg) {
  var f, obj = {
    traceId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intrinsicsMap: (f = msg.getIntrinsicsMap()) ? f.toObject(includeInstance, proto.com.newrelic.trace.v1.AttributeValue.toObject) : [],
    userAttributesMap: (f = msg.getUserAttributesMap()) ? f.toObject(includeInstance, proto.com.newrelic.trace.v1.AttributeValue.toObject) : [],
    agentAttributesMap: (f = msg.getAgentAttributesMap()) ? f.toObject(includeInstance, proto.com.newrelic.trace.v1.AttributeValue.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.newrelic.trace.v1.Span}
 */
proto.com.newrelic.trace.v1.Span.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.newrelic.trace.v1.Span;
  return proto.com.newrelic.trace.v1.Span.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.newrelic.trace.v1.Span} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.newrelic.trace.v1.Span}
 */
proto.com.newrelic.trace.v1.Span.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    case 2:
      var value = msg.getIntrinsicsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.newrelic.trace.v1.AttributeValue.deserializeBinaryFromReader, "");
         });
      break;
    case 3:
      var value = msg.getUserAttributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.newrelic.trace.v1.AttributeValue.deserializeBinaryFromReader, "");
         });
      break;
    case 4:
      var value = msg.getAgentAttributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.newrelic.trace.v1.AttributeValue.deserializeBinaryFromReader, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.newrelic.trace.v1.Span.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.newrelic.trace.v1.Span.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.newrelic.trace.v1.Span} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.newrelic.trace.v1.Span.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTraceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntrinsicsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.newrelic.trace.v1.AttributeValue.serializeBinaryToWriter);
  }
  f = message.getUserAttributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.newrelic.trace.v1.AttributeValue.serializeBinaryToWriter);
  }
  f = message.getAgentAttributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(4, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.newrelic.trace.v1.AttributeValue.serializeBinaryToWriter);
  }
};


/**
 * optional string trace_id = 1;
 * @return {string}
 */
proto.com.newrelic.trace.v1.Span.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.newrelic.trace.v1.Span.prototype.setTraceId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * map<string, AttributeValue> intrinsics = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.newrelic.trace.v1.AttributeValue>}
 */
proto.com.newrelic.trace.v1.Span.prototype.getIntrinsicsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.newrelic.trace.v1.AttributeValue>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.com.newrelic.trace.v1.AttributeValue));
};


proto.com.newrelic.trace.v1.Span.prototype.clearIntrinsicsMap = function() {
  this.getIntrinsicsMap().clear();
};


/**
 * map<string, AttributeValue> user_attributes = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.newrelic.trace.v1.AttributeValue>}
 */
proto.com.newrelic.trace.v1.Span.prototype.getUserAttributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.newrelic.trace.v1.AttributeValue>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      proto.com.newrelic.trace.v1.AttributeValue));
};


proto.com.newrelic.trace.v1.Span.prototype.clearUserAttributesMap = function() {
  this.getUserAttributesMap().clear();
};


/**
 * map<string, AttributeValue> agent_attributes = 4;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.newrelic.trace.v1.AttributeValue>}
 */
proto.com.newrelic.trace.v1.Span.prototype.getAgentAttributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.newrelic.trace.v1.AttributeValue>} */ (
      jspb.Message.getMapField(this, 4, opt_noLazyCreate,
      proto.com.newrelic.trace.v1.AttributeValue));
};


proto.com.newrelic.trace.v1.Span.prototype.clearAgentAttributesMap = function() {
  this.getAgentAttributesMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.newrelic.trace.v1.AttributeValue = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_);
};
goog.inherits(proto.com.newrelic.trace.v1.AttributeValue, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.newrelic.trace.v1.AttributeValue.displayName = 'proto.com.newrelic.trace.v1.AttributeValue';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.com.newrelic.trace.v1.AttributeValue.ValueCase = {
  VALUE_NOT_SET: 0,
  STRING_VALUE: 1,
  BOOL_VALUE: 2,
  INT_VALUE: 3,
  DOUBLE_VALUE: 4
};

/**
 * @return {proto.com.newrelic.trace.v1.AttributeValue.ValueCase}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.getValueCase = function() {
  return /** @type {proto.com.newrelic.trace.v1.AttributeValue.ValueCase} */(jspb.Message.computeOneofCase(this, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.toObject = function(opt_includeInstance) {
  return proto.com.newrelic.trace.v1.AttributeValue.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.newrelic.trace.v1.AttributeValue} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.newrelic.trace.v1.AttributeValue.toObject = function(includeInstance, msg) {
  var f, obj = {
    stringValue: jspb.Message.getFieldWithDefault(msg, 1, ""),
    boolValue: jspb.Message.getFieldWithDefault(msg, 2, false),
    intValue: jspb.Message.getFieldWithDefault(msg, 3, 0),
    doubleValue: +jspb.Message.getFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.newrelic.trace.v1.AttributeValue}
 */
proto.com.newrelic.trace.v1.AttributeValue.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.newrelic.trace.v1.AttributeValue;
  return proto.com.newrelic.trace.v1.AttributeValue.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.newrelic.trace.v1.AttributeValue} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.newrelic.trace.v1.AttributeValue}
 */
proto.com.newrelic.trace.v1.AttributeValue.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringValue(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolValue(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setIntValue(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDoubleValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.newrelic.trace.v1.AttributeValue.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.newrelic.trace.v1.AttributeValue} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.newrelic.trace.v1.AttributeValue.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional string string_value = 1;
 * @return {string}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.getStringValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.newrelic.trace.v1.AttributeValue.prototype.setStringValue = function(value) {
  jspb.Message.setOneofField(this, 1, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], value);
};


proto.com.newrelic.trace.v1.AttributeValue.prototype.clearStringValue = function() {
  jspb.Message.setOneofField(this, 1, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.hasStringValue = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool bool_value = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.getBoolValue = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.com.newrelic.trace.v1.AttributeValue.prototype.setBoolValue = function(value) {
  jspb.Message.setOneofField(this, 2, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], value);
};


proto.com.newrelic.trace.v1.AttributeValue.prototype.clearBoolValue = function() {
  jspb.Message.setOneofField(this, 2, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.hasBoolValue = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 int_value = 3;
 * @return {number}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.getIntValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.newrelic.trace.v1.AttributeValue.prototype.setIntValue = function(value) {
  jspb.Message.setOneofField(this, 3, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], value);
};


proto.com.newrelic.trace.v1.AttributeValue.prototype.clearIntValue = function() {
  jspb.Message.setOneofField(this, 3, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.hasIntValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double double_value = 4;
 * @return {number}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.getDoubleValue = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.com.newrelic.trace.v1.AttributeValue.prototype.setDoubleValue = function(value) {
  jspb.Message.setOneofField(this, 4, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], value);
};


proto.com.newrelic.trace.v1.AttributeValue.prototype.clearDoubleValue = function() {
  jspb.Message.setOneofField(this, 4, proto.com.newrelic.trace.v1.AttributeValue.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.newrelic.trace.v1.AttributeValue.prototype.hasDoubleValue = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.newrelic.trace.v1.RecordStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.newrelic.trace.v1.RecordStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.newrelic.trace.v1.RecordStatus.displayName = 'proto.com.newrelic.trace.v1.RecordStatus';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.newrelic.trace.v1.RecordStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.com.newrelic.trace.v1.RecordStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.newrelic.trace.v1.RecordStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.newrelic.trace.v1.RecordStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    messagesSeen: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.newrelic.trace.v1.RecordStatus}
 */
proto.com.newrelic.trace.v1.RecordStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.newrelic.trace.v1.RecordStatus;
  return proto.com.newrelic.trace.v1.RecordStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.newrelic.trace.v1.RecordStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.newrelic.trace.v1.RecordStatus}
 */
proto.com.newrelic.trace.v1.RecordStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMessagesSeen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.newrelic.trace.v1.RecordStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.newrelic.trace.v1.RecordStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.newrelic.trace.v1.RecordStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.newrelic.trace.v1.RecordStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessagesSeen();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
};


/**
 * optional uint64 messages_seen = 1;
 * @return {number}
 */
proto.com.newrelic.trace.v1.RecordStatus.prototype.getMessagesSeen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.newrelic.trace.v1.RecordStatus.prototype.setMessagesSeen = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.com.newrelic.trace.v1);
