/*
 * Copyright 2026 New Relic Corporation. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

'use strict'

const { EventEmitter } = require('node:events')
const stringify = require('json-stringify-safe')
const defaultLogger = require('#agentlib/logger.js').child({
  component: 'config'
})
const featureFlags = require('#agentlib/feature-flags.js')
const parseLabels = require('#agentlib/util/label-parser.js')
const flatten = require('#agentlib/util/flatten.js')
const { parseKey } = require('#agentlib/collector/key-parser.js')

const configOwnProperty = require('./config-own-property.js')
const findConfigFile = require('./find-config-file.js')
const redactValue = require('./redact-value.js')
const validateConfig = require('./validate-config.js')
const { boolean } = require('./formatters.js')
const { generateDefaultConfig } = require('./generate-default-config.js')
const { applyEnvironmentOverrides } = require('./apply-environment-overrides.js')
const {
  buildSamplers,
  isValidDTSampler
} = require('./samplers.js')
const AttributeFilter = require('./attribute-filter.js')

const defaultConfig = generateDefaultConfig()

const AZURE_APP_NAME = 'APP_POOL_ID'
const BASE_CONFIG_PATH = require.resolve('../../newrelic')
const DEFAULT_MAX_PAYLOAD_SIZE_IN_BYTES = 1_000_000
const HSM = require('./hsm.js')
const REMOVE_BEFORE_SEND = new Set(['attributeFilter'])
const SERVERLESS_DT_KEYS = [
  'account_id',
  'primary_application_id',
  'trusted_account_key'
]
const TLS_WARNING = 'SSL config key can no longer be disabled, not updating.'

/**
 * A list of object key names which have an object value that itself contains
 * a set of arbitrary key-values that we want to copy over wholesale. By
 * default, we only copy over values that we know about. But the fields listed
 * in this set are an exception.
 *
 * @type {Set<string>}
 */
const HAS_ARBITRARY_KEYS = new Set([
  // `ignore_messages` and `expected_messages` map error-like object instances
  // to sets of messages. Each key in these objects represents a class name.
  // Each key maps to an array of string messages. So, if the user has a custom
  // error class named `MyError`, the following settings could be specified:
  //
  // - `ignore_messages: { MyError: ['foo', 'bar'] }`
  // - `expected_messages: { MyError: ['baz'] }`
  'ignore_messages',
  'expected_messages',

  // `labels` is an arbitrary set of key-values that describe a "tag" system.
  // These tags get attached to all logs, and possibly other data entities,
  // that are generated by the agent/application. The key is the tag name and
  // the value is the tag value. So `{ foo: 'bar' }` indicates that the tag
  // "foo" should be attached, and it should always have the value "bar".
  'labels'
])

let cachedInstance

/**
 * Represents all configurable properties of the agent. Note that this object
 * gets serialized and shipped to the collector at least once during an
 * application's lifecycle. This means we utilize mutable public fields
 * in order to simplify this process (i.e. all public fields get serialized
 * and shipped).
 *
 * @class
 * @alias AgentConfig
 */
class Config extends EventEmitter {
  #logger

  #appName = []
  #ssl = true

  constructor(inputConfig, { logger = defaultLogger } = {}) {
    super()
    this.#logger = logger

    // Apply the default configuration before attempting any overrides. Deep
    // clone it so nested objects (e.g. `labels`) are owned by this instance;
    // `generateDefaultConfig` returns a shared, cached object, and a shallow
    // copy would let later merges mutate that shared default across instances.
    Object.assign(this, structuredClone(defaultConfig))

    // Ordering is important here. We must apply new values from the order
    // of leat priority to hightest priority.
    this.#initFeatureFlags()
    this.#initInternalFields()
    this.#applyUserValues(inputConfig)
    this.#applySpecialValues()
    this.#applyFeatureFlagsFromEnv()
    this.#applyEnvironmentOverrides()
    this.#finalizeValues()
    this.#applyServerlessConfig(inputConfig)

    if (this.high_security) {
      this.#applyHighSecurity()
    }

    this.version = require('../../package.json').version

    // Now set up things that require all configuration settings to be in their
    // finalized state:
    this.attributeFilter = new AttributeFilter(this)
    this.parsedLabels = parseLabels(this.labels, this.#logger)
    this.#setApplicationLoggingLabels()

    // We emit from the process because we have a chicken-and-egg sitution
    // with the logger and the configuration management. The configuration
    // specifies the logging config, but we want a logger so that we can
    // log important details about configuration processing. To solve this,
    // the first thing the agent bootstrap process does is to create a
    // buffering logger. This logger will buffer any logs issued through it
    // until the logger instance is reconfigured to its final state. Thus, we
    // issue this signal when the configuration bootstrapping has completed
    // so that the logger can reconfigure itself and flush its queue.
    process.emit('nr-config-load-complete', this)
  }

  /**
   * Convenience method primarily used in testing.
   *
   * @param {object} inputConfig The initial configuration state.
   *
   * @private
   * @returns {AgentConfig}
   */
  static createInstance(inputConfig) {
    cachedInstance = Config.initialize(inputConfig)
    return cachedInstance
  }

  /**
   * Convenience method used internally.
   *
   * @private
   * @returns {AgentConfig|undefined}
   */
  static getInstance() {
    return cachedInstance
  }

  /**
   * This is the primary interface for getting a configuration instance. It
   * handles caching of a valid configuration. If the discovered configuration,
   * from a `newrelic.js` and/or environment variables, contains an invalid
   * structure, this will return a stub config to allow the agent to
   * initialize itself to a non-working, but not application crashing, state.
   *
   * @returns {AgentConfig} The built configuration.
   */
  static getOrCreateInstance() {
    if (cachedInstance !== undefined) return cachedInstance

    try {
      cachedInstance = Config.initialize()
    } catch (error) {
      console.error('New Relic for Node.js is disabled due to an error:')
      console.error(error.stack)

      // Config construction has potential to throw due to invalid settings.
      // This allows the agent to return a stub api without crashing the process.
      cachedInstance = Object.assign(
        Object.create(null),
        structuredClone(defaultConfig),
        {
          agent_enabled: false,
          logging: {
            enabled: true,
            filepath: 'stdout'
          }
        }
      )
      cachedInstance.setLogger = Config.prototype.setLogger
    }

    return cachedInstance
  }

  /**
   * Create a new configuration instance. If a configuration object is passed in,
   * it will be validated and used to return a new {@link Config} object without
   * attempting to load values from the standard locations.
   *
   * When a base configuration object is not passed in, the standard config
   * locations will be loaded in order (from a `newrelic.js` file):
   *
   * 1. The process's current working directory.
   * 2. The same directory as the process's main module ( i.e. the script passed
   * to node on the command line).
   * 3. The directory pointed to by the NEW_RELIC_HOME
   * environment variable.
   * 4. The current process's HOME directory.
   * 5. The directory immediately above the `node_modules` directory that contains
   * the `newrelic` module installation.
   *
   * When recognized environment variables are present, and a config file has
   * been loaded, the environment variables will override any settings loaded
   * from the file.
   *
   * Important: this function bubbles up errors. It is intended that the agent
   * bootstrap process recognizes these thrown errors and does the right thing
   * without crashing the process.
   *
   * @param {object} [config] Initial configuration. Values from other sources
   * may overwrite values present in this object.
   * @param {object} [deps] Optional dependencies.
   * @param {AgentLogger} [deps.logger] Logger instance.
   *
   * @throws {Error} When the configuration cannot be validated or read from
   * disk.
   *
   * @returns {AgentConfig} Instantiated configuration object.
   */
  static initialize(config, { logger = defaultLogger } = {}) {
    if (config != null) {
      validateConfig(config)
      return new (this)(config)
    }

    if (boolean(process.env.NEW_RELIC_NO_CONFIG_FILE) === true) {
      logger.info('NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables.')
      return new (this)()
    }

    const filepath = findConfigFile()
    if (filepath === undefined) {
      logger.info(
        [
          'Unable to find configuration file.',
          'If a configuration file is desired (common for non-containerized environments),',
          `a base configuration file can be copied from ${BASE_CONFIG_PATH}`,
          'and renamed to "newrelic.js" in the directory from which you will start',
          'your application.',
          'Attempting to start agent using environment variables.'
        ].join(' ')
      )

      return new (this)()
    }

    let userConf
    try {
      userConf = require(filepath).config
    } catch (error) {
      logger.error(error)
      logger.warn(
        [
          `Unable to read existing configuration file "${filepath}".`,
          'To allow reading of the file (if desired),',
          'please ensure the application has read access and the file is exporting valid JSON.',
          'Attempting to start agent using environment variables.'
        ].join(' ')
      )
    }
    if (userConf === undefined) {
      return new (this)()
    }

    validateConfig(userConf)
    const finalConfig = new (this)(userConf)
    finalConfig.config_file_path = filepath
    logger.debug('Using configuration file %s.', filepath)

    finalConfig.validateFlags()

    return finalConfig
  }

  // -- BEGIN: Private methods
  // -- Private methods are wholly internal to the operation of the
  // -- configuration object. No other user of the configuration should need
  // -- to access anything a private method provides.

  /**
   * Overrides default and user set configuration with values found in the
   * environment.
   */
  #applyEnvironmentOverrides() {
    applyEnvironmentOverrides(this, { logger: this.#logger })
  }

  /**
   * Overrides default and user set feature flag settings with those found
   * set in the environment.
   */
  #applyFeatureFlagsFromEnv() {
    const flags = Object.keys(featureFlags.prerelease).concat(featureFlags.released)
    for (const flag of flags) {
      const val = process.env['NEW_RELIC_FEATURE_FLAG_' + flag.toUpperCase()]
      if (val) {
        this.feature_flag[flag] = boolean(val)
      }
    }
  }

  /**
   * Iterate through the high security sensitive fields and coerce them into
   * compliant values.
   */
  #applyHighSecurity() {
    const config = this
    const logger = this.#logger

    checkNode('', this, HSM.HIGH_SECURITY_SETTINGS)

    // As a one-off, we add a global exclude rule to the list to keep from
    // clobbering user defined rules:
    this.attributes.exclude.push('request.parameters.*')

    function checkNode(base, target, settings) {
      for (const key of Object.keys(settings)) {
        checkKey(base, target, settings, key)
      }
    }

    function checkKey(base, target, settings, key) {
      const hsValue = settings[key]

      if (hsValue && typeof hsValue === 'object' && Array.isArray(hsValue) === false) {
        if (typeof target[key] !== 'object') {
          logger.warn('High Security Mode: %s should be an object, found %s', key, target[key])
          target[key] = Object.create(null)
        }

        return checkNode(base + key + '.', target[key], hsValue)
      }

      if (target[key] !== hsValue) {
        logger.warn('High Security Mode: %s was set to %s, coercing to %s', key, target[key], hsValue)
        target[key] = hsValue
        config.emit(base + key, hsValue)
      }
    }
  }

  #applyServerlessConfig(inputConfig) {
    if (!this.serverless_mode.enabled) {
      this.#preventServerlessDT()
      return
    }

    this.#setServerlessAppName()
    this.#setServerlessInfiniteTracing()
    this.#setServerlessLogging(inputConfig)
    this.#setServerlessNativeMetrics(inputConfig)
    this.#setServerlessDT()
  }

  /**
   * Handles special cases that are only triggered under specific circumstances.
   * As of 2026-09, this only handles the case where a user has not specified
   * a name for their application in their parsed configuration but that
   * application is running in Azure, where we can query for the environment
   * for the name.
   */
  #applySpecialValues() {
    const name = this.app_name
    if (name == null || name.length === 0) {
      const azureName = process.env[AZURE_APP_NAME]
      if (azureName) this.app_name = azureName.split(',')
    }
  }

  /**
   * Recursively iterates a provided configuration object, i.e. deeply walks
   * the tree of objects, and copies the values from that object to the
   * configuration instance.
   *
   * @param {object} inputConfig The configuration object to walk and pull
   * values from. This object will be mutated.
   * @param {object} [destination] The object to copy values to.
   * @param {boolean} [allowUnknownKeys] When set to `true`, the function will
   * blindly copy key-values from the input over to the destination. Otherwise,
   * only recognized configuration keys will be processed.
   */
  #applyUserValues(inputConfig, destination = this, allowUnknownKeys = false) {
    if (!inputConfig) return

    for (const key of Object.keys(inputConfig)) {
      if (
        allowUnknownKeys === false &&
        configOwnProperty(destination, key) === false
      ) {
        // The passed in configuration contains a key that is not defined in
        // our default configuration, and we are not accepting such keys.
        // So move on to the next.
        continue
      }

      if (isValidDTSampler(key) === true) {
        buildSamplers({
          config: inputConfig,
          configToUpdate: destination,
          logger: this.#logger,
          key
        })
      }

      if (key === 'ssl' && boolean(inputConfig.ssl) === false) {
        this.#logger.warn(TLS_WARNING)
        continue
      }

      let node
      try {
        node = inputConfig[key]
      } catch {
        this.#logger.warn('Error thrown on access of user config for key: %s', key)
        continue
      }

      if (
        typeof node === 'object' &&
        Array.isArray(node) === false &&
        (node instanceof RegExp) === false
      ) {
        const allowArbitrary =
          // Top-level keys are allowed.
          destination === this ||
          // The key explicitly allows for arbitrary keys.
          HAS_ARBITRARY_KEYS.has(key)
        this.#applyUserValues(node, destination[key], allowArbitrary)
      } else {
        // It's a scalar value. So we can simply copy it over.
        destination[key] = node
      }
    }
  }

  /**
   * Some configuration values require extra processing to finalize their
   * format to the correct one. This method is used to accomplish this for
   * all such values.
   */
  #finalizeValues() {
    const statusCodes = this.error_collector?.ignore_status_codes
    if (statusCodes) {
      this.error_collector.ignore_status_codes = this.#parseStatusCodes(statusCodes)
    }

    const expectedCodes = this.error_collector?.expected_status_codes
    if (expectedCodes) {
      this.error_collector.expected_status_codes = this.#parseStatusCodes(expectedCodes)
    }

    const grpcStatusCodes = this.grpc?.ignore_status_codes
    if (grpcStatusCodes) {
      this.grpc.ignore_status_codes = this.#parseStatusCodes(grpcStatusCodes)
    }

    const logAliases = {
      verbose: 'trace',
      debugging: 'debug',
      warning: 'warn',
      err: 'error'
    }
    const level = this.logging.level
    this.logging.level = logAliases[level] || level

    const region = parseKey(this.license_key)
    if (this.host === '') {
      this.host = region
        ? `collector.${region}.nr-data.net`
        : 'collector.newrelic.com'
    }

    if (this.license_key) {
      this.license_key = this.license_key.trim()
    }

    this.redacted_license_key = redactValue(this.license_key)

    if (!this.event_harvest_config) {
      this.event_harvest_config = {
        report_period_ms: 60_000,
        harvest_limits: {
          analytic_event_data: this.transaction_events.max_samples_stored,
          custom_event_data: this.custom_insights_events.max_samples_stored,
          error_event_data: this.error_collector.max_event_samples_stored,
          span_event_data: this.span_events.max_samples_stored,
          log_event_data: this.application_logging.forwarding.max_samples_stored
        }
      }
    }
  }

  /**
   * Feature flags are mostly private settings for gating unreleased features.
   */
  #initFeatureFlags() {
    this.feature_flag = Object.create(null)
    Object.assign(this.feature_flag, featureFlags.prerelease)
  }

  /**
   * Sets the default values for internal configuration fields that we do
   * not expect to be set by users.
   */
  #initInternalFields() {
    // The `newrelic_home` and `config_file_path` fields are a bit of a
    // mystery to current maintainers (2026-09). The `newrelic_home` field is
    // only set when the NEW_RELIC_HOME environment variable is set, and it
    // only specifies the directory that maybe contains a `newrelic.js` config
    // file. The `config_file_path` field is set by the `initialize` function.
    // It indicates the full filepath to the `newrelic.js` file that was
    // actually loaded for user configuration. It is possible for neither
    // field to be set.
    this.newrelic_home = null
    this.config_file_path = null

    // The following fields are set by the collector during the connect cycle.
    this.run_id = null
    this.account_id = null
    this.application_id = null
    this.web_transactions_apdex = Object.create(null)
    this.encoding_key = null
    this.primary_application_id = null
    this.trusted_account_ids = null
    this.trusted_account_key = null

    // The global sampling target for AdaptiveSamplers that do not
    // specify their own sampling_target
    this.setSamplingTarget(
      this.distributed_tracing.sampler.adaptive_sampling_target
    )
    this.sampling_target_period_in_seconds = 60
    this.max_payload_size_in_bytes = DEFAULT_MAX_PAYLOAD_SIZE_IN_BYTES

    // this value is arbitrary
    this.max_trace_segments = 900

    this.entity_guid = null

    // feature level of this account
    this.product_level = 0
    // product-level related
    this.collect_traces = true
    this.collect_errors = true
    this.collect_span_events = true

    this.browser_monitoring.loader = 'rum'
    this.browser_monitoring.loader_version = ''
    // default to empty object, this will get populated
    // from `onConnect` if hybrid agent is enabled
    // along with hybrid agent's metrics feature
    this.otlp_resource_attributes = {}

    // Settings to play nice with DLPs (see NODE-1044).
    this.simple_compression = false // Disables subcomponent compression
    this.put_for_data_send = false // Changes http verb for harvest
  }

  /**
   * Given a range string like `100 - 200`, parse the string into the full
   * set of integers and add them to the provided `store`. Allowed ranges
   * are between 0 and 1000, inclusive.
   *
   * @param {string} range Status codes range string.
   * @param {string[]} store An array to append parsed range numbers to.
   *
   * @returns {number[]} The mutated `store` instance.
   */
  #parseRange(range, store) {
    const parts = range.split('-')

    if (parts.length !== 2) {
      this.#logger.warn('Failed to parse range %s', range)
      return store
    }

    if (parts[0] === '') {
      // Handle a negative code, e.g. `-7`.
      return store.push(
        parseInt(range, 10)
      )
    }

    const lower = parseInt(parts[0], 10)
    const upper = parseInt(parts[1], 10)
    if (Number.isNaN(lower) || Number.isNaN(upper)) {
      this.#logger.warn('Range must contain two numbers %s', range)
      return store
    }
    if (lower > upper) {
      this.#logger.warn('Range must start with lower bound %s', range)
    } else if (lower < 0 || upper > 1_000) {
      this.#logger.warn('Range must be between 0 and 1000 %s', range)
    } else {
      for (let i = lower; i <= upper; i += 1) {
        store.push(i)
      }
    }

    return store
  }

  /**
   * Parse a single status code string, or a status code range string, into
   * a number or set of numbers.
   *
   * @param {string} statusCodes The status code or range string to parse.
   *
   * @returns {number[]} The parsed status codes.
   */
  #parseStatusCodes(statusCodes) {
    const parsedCodes = []
    for (const statusCode of statusCodes) {
      if (typeof statusCode === 'string' && statusCode.indexOf('-') !== -1) {
        this.#parseRange(statusCode, parsedCodes)
        continue
      }

      const parsedCode = parseInt(statusCode, 10)
      if (Number.isNaN(parsedCode) === false) {
        parsedCodes.push(parsedCode)
      } else {
        this.#logger.warn('Failed to parse status code %s', statusCode)
      }
    }
    return parsedCodes
  }

  /**
   * In serverless mode, we defer auth to the downstream serverless entities.
   * This means we set `account_id`, `primary_application_id`, and
   * `trusted_account_key` in configuration. This function sets all of those to
   * `null` because `serverless_mode.enabled` is falsey.
   */
  #preventServerlessDT() {
    for (const key of SERVERLESS_DT_KEYS) {
      if (!this[key]) continue
      this.#logger.warn(
        key +
        ' was configured locally without enabling serverless_mode. ' +
        'This local value will be ignored and set by the New Relic servers.'
      )
      this[key] = null
    }
  }

  /**
   * Compares the labels list to the application logging excluded label list and
   * removes any labels that need to be excluded. Each label is then
   * prefixed with `tags.`.
   */
  #setApplicationLoggingLabels() {
    if (this.application_logging.forwarding.labels.enabled === false) {
      return
    }

    this.application_logging.forwarding.labels.exclude =
      this.application_logging.forwarding.labels.exclude.map((k) => k.toLowerCase())
    const exclude = this.application_logging.forwarding.labels.exclude
    const filteredLabels = {}
    for (const label of this.parsedLabels) {
      if (exclude.includes(label.label_type.toLowerCase()) !== false) {
        continue
      }
      // The parsed label is not listed in the "exclude labels" set, so
      // we add it to the set of labels that will be applied.
      filteredLabels[`tags.${label.label_type}`] = label.label_value
    }

    this.loggingLabels = filteredLabels
  }

  #setServerlessAppName() {
    if (this.app_name && this.app_name.length > 0) return

    const namingSource = process.env.AWS_LAMBDA_FUNCTION_NAME
      ? 'process.env.AWS_LAMBDA_FUNCTION_NAME'
      : 'DEFAULT'
    const name = process.env.AWS_LAMBDA_FUNCTION_NAME || 'Serverless Application'
    this.app_name = [name]
    this.#logger.info(
      "Auto-naming serverless application to ['%s'] from: %s",
      name,
      namingSource
    )
  }

  /**
   * Distributed tracing requires an account id. The account id is not typically
   * set in serverless environments. When the account is not present, disable
   * DT. Otherwise, normalize sibling values.
   */
  #setServerlessDT() {
    if (!this.account_id) {
      if (this.distributed_tracing.enabled) {
        this.#logger.warn(
          'Using distributed tracing in serverless mode requires account_id be ' +
          'defined, either in your newrelic.js file or via environment variables. ' +
          'Disabling distributed tracing.'
        )
        this.distributed_tracing.enabled = false
      }
    } else {
      // default trusted_account_key to account_id
      this.trusted_account_key = this.trusted_account_key || this.account_id

      // Not required in serverless mode but must default to Unknown to function.
      this.primary_application_id = this.primary_application_id || 'Unknown'
    }
  }

  #setServerlessInfiniteTracing() {
    if (this.infinite_tracing.trace_observer.host) {
      this.infinite_tracing.trace_observer.host = ''
      this.infinite_tracing.trace_observer.port = ''
      this.#logger.info('Infinite tracing is explicitly disabled in serverless_mode.')
    }
  }

  /**
   * Disables logging when not explicitly enabled via a user config file or
   * the environment variable. Logging in serverless mode requires special
   * consideration.
   *
   * @param {object} inputConfig The configuration object passed in to the
   * constructor. It is used to determine if the value was set via a config
   * file.
   */
  #setServerlessLogging(inputConfig) {
    const inputEnabled = inputConfig?.logging?.enabled
    const envEnabled = process.env.NEW_RELIC_LOG_ENABLED

    if (inputEnabled === undefined && envEnabled === undefined) {
      this.logging.enabled = false

      this.#logger.info(
        'Logging is disabled by default when serverless_mode is enabled. ' +
        'If desired, enable logging via config file or environment variable and ' +
        'set filepath to a valid path for current environment, stdout or stderr.'
      )
    }
  }

  /**
   * Disables native metrics when not explicitly enabled via a user config file
   * or the environment variable. Native metrics in serverless has limited
   * benefit and will drastically decrease cold start time.
   *
   * @param {object} inputConfig The configuration object passed in to the
   * constructor. It is used to determine if the value was set via a config
   * file.
   */
  #setServerlessNativeMetrics(inputConfig) {
    const inputEnabled = inputConfig?.plugins?.native_metrics?.enabled
    const envEnabled = process.env.NEW_RELIC_NATIVE_METRICS_ENABLED

    if (
      (inputEnabled !== undefined || envEnabled !== undefined) &&
      this.plugins.native_metrics.enabled
    ) {
      this.#logger.info(
        'Enabling the native-metrics module when in serverless mode may greatly ' +
        'increase cold-start times. Given the limited benefit of the VM metrics' +
        'and general lack of control in a serverless environment, we do not ' +
        'recommend this trade-off.'
      )
    } else {
      this.plugins.native_metrics.enabled = false
      this.#logger.info(
        'The native-metrics module is disabled by default when serverless_mode ' +
        'is enabled. If desired, enable the native-metrics module via config file ' +
        'or environment variable.'
      )
    }
  }

  // -- BEGIN: Public methods
  // -- Public methods are not necessarily "public" in the sense that anyone
  // -- should be able to use them. They are public in the sense that they
  // -- provide utility to other parts of the internal code base.

  /**
   * Retrieve the configured application name as a spec compliant array of
   * application names, regardless of stored value.
   *
   * @returns {string[]} The app name list, or an empty list.
   */
  applications() {
    const apps = this.app_name
    if (Array.isArray(apps) === true && apps.length > 0) {
      return apps
    }
    if (apps && typeof apps === 'string') {
      return [apps]
    }
    return []
  }

  /**
   * Used to generate a JSON compatible object for use in reporting our
   * configured settings to the collector. It filters out keys that are meant
   * to be wholly internal, and keys that run afoul of the high security mode
   * settings being enforced.
   *
   * @returns {object} The filtered configuration object.
   */
  publicSettings() {
    let settings = Object.create(null)

    // Own enumerable data properties, plus any getter-backed properties defined
    // on the prototype (e.g. `app_name`). Class getters are non-enumerable and
    // live on the prototype, so `for..in` alone does not surface them.
    const keys = new Set(Object.keys(this))
    for (const name of Object.getOwnPropertyNames(Config.prototype)) {
      if (Object.getOwnPropertyDescriptor(Config.prototype, name).get) {
        keys.add(name)
      }
    }

    for (const key of keys) {
      if (REMOVE_BEFORE_SEND.has(key) === true) {
        continue
      }
      if (HSM.REDACT_BEFORE_SEND.has(key) === true) {
        settings[key] = redactValue(this[key], { fullRedaction: true })
      } else if (HSM.REMOVE_BEFORE_SEND.has(key) === false) {
        settings[key] = this[key]
      }
    }

    // Agent-side setting is 'enable', but collector-side setting is
    // 'auto_instrument'. Send both values up.
    settings.browser_monitoring.auto_instrument = settings.browser_monitoring.enable

    try {
      settings = stringify(settings)
      // Remove simple circular references
      settings = flatten(Object.create(null), '', JSON.parse(settings))
    } catch (err) {
      this.#logger.error(err, 'Unable to stringify settings object')
    }
    return settings
  }

  /**
   * Used to verify that the `feature_flag` configuration is valid. Currently,
   * it is only used by the static {@link #initialize} method and directly
   * from unit test. It's not clear if customers are directly setting
   * feature flags or if they only ever do it from a configuration source.
   * Ideally, we wouldn't need to run a separate method to generate these
   * warnings, and we would instead issue the warning when the flag is being
   * set. But in order to do that with the current design, we'd have to resort
   * to using a `Proxy`. Proxies are slow by their nature, and it doesn't seem
   * worth the cost/effort to redesign this right now (2026-09).
   *
   * @private
   */
  validateFlags() {
    for (const key of Object.keys(this.feature_flag)) {
      if (featureFlags.released.includes(key) === true) {
        this.#logger.warn('Feature flag %s has been released', key)
      }
      if (featureFlags.unreleased.includes(key) === true) {
        this.#logger.warn('Feature flag %s has been deprecated', key)
      }
    }
  }

  // -- BEGIN: Getter and setter INSTANCE methods
  // -- We use getter and setter methods instead of prototype getters and
  // -- setters because when we generate a JSON compatible representation
  // -- we need to iterate all of the object's own properties and native
  // -- getters and setters will be included in that list. By using method
  // -- variants, we are able to add conveniences for ourselves and retain
  // -- the ability to generate a JSON compatible representation of the
  // -- actual configuration properties.

  /**
   * Convenience accessor to the adaptive sampling target value.
   *
   * @returns {number|undefined} The adaptive sampling target.
   */
  getSamplingTarget() {
    return this.distributed_tracing.sampler.adaptive_sampling_target
  }

  /**
   * Convenience setter for the adaptive sampling target. Emits a
   * `sampling_target` event so listeners (e.g. the agent) can react.
   *
   * @param {number} value The target threshold value.
   */
  setSamplingTarget(value) {
    this.distributed_tracing.sampler.adaptive_sampling_target = value
    this.emit('sampling_target', value)
  }

  // -- BEGIN: Getter and setter PROTOTYPE methods
  // -- These methods are used for properties that need to be included when
  // -- we generate a JSON compatible object for serialization in order to
  // -- ship the data to the collector. Unlike the instance getter/setter
  // -- methods, these will be iterated during serialization. So, if the
  // -- property SHOULD NOT be included in the serialized form, DO NOT add
  // -- the getter and setter below. Add instance methods instead.

  /**
   * The configured application name(s), always as an array.
   *
   * @returns {Array} The application names.
   */
  get app_name() {
    return this.#appName
  }

  /**
   * Normalizes the application name on assignment, from whatever source (user
   * config, environment, Azure APP_POOL_ID, server-side config). A string is
   * split on `;`/`,` and trimmed into an array; arrays and null/undefined are
   * stored as-is.
   *
   * @param {string|Array|null} value The application name(s).
   */
  set app_name(value) {
    this.#appName = typeof value === 'string'
      ? value.split(/[;,]/).map((name) => name.trim())
      : value
  }

  get ssl() {
    return this.#ssl
  }

  set ssl(value) {
    const v = boolean(value)
    if (v !== true) {
      this.#logger.warn(TLS_WARNING)
      this.#ssl = true
      return
    }

    this.#ssl = v
  }
}

module.exports = Config
