#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff-index --cached --name-only HEAD)
for FILE in $STAGED_FILES
do
  echo "name of file $FILE"
  if [ $FILE == "package.json" ]; then
    RUN_THIRD_PARTY=1
    break
  fi
done

if [ -n "$RUN_THIRD_PARTY" ]; then
  echo "package.json changed, running oss manifest and notices"
  npm run third-party-updates
fi

npx lint-staged


