name: Prepare Agent Release PR

# Manual trigger only
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release. patch or minor (major if breaking)'
        required: true
        default: 'patch'

jobs:
  agent-release-notes:
    uses: newrelic/node-newrelic/.github/workflows/prep-release.yml@main
    with:
      release_type: ${{ github.event.inputs.release_type }}
      use_new_release: ${{ vars.USE_NEW_RELEASE }}
